import numpy as np
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot
import pdb
benign = np.load('/home/Drive2/aditya/Benign.npy')
insitu = np.load('/home/Drive2/aditya/InSitu.npy')
invasive = np.load('/home/Drive2/aditya/Invasive.npy')
normal = np.load('/home/Drive2/aditya/Normal.npy')
pdb.set_trace()

benign_hist = np.zeros((25,4))
insitu_hist = np.zeros((25,4))
invasive_hist = np.zeros((25,4))
normal_hist = np.zeros((25,4))

for i in range(25):
    benign_hist[i,0] = (benign[i,:] == 0).sum()
    benign_hist[i,1] = (benign[i,:] == 1).sum()
    benign_hist[i,2] = (benign[i,:] == 2).sum()
    benign_hist[i,3] = (benign[i,:] == 3).sum()
    benign_hist[i,:] = benign_hist[i,:]/len(benign[i,:])
    print(np.sum(benign_hist[i,:]))
    #pyplot.figure(i*4)
    pyplot.bar([0,1,2,3],benign_hist[i,:],1,0,'center')
    pyplot.xlabel('0:Benign 1:InSitu 2:Invasive 3:Normal')
    pyplot.ylabel('Percent')
    pyplot.title('Benign'+str(i))
    pyplot.savefig('/home/Drive2/aditya/Histograms/Benign_'+str(i)+'.png')
    pyplot.close()

    insitu_hist[i,0] = (insitu[i,:] == 0).sum()
    insitu_hist[i,1] = (insitu[i,:] == 1).sum()
    insitu_hist[i,2] = (insitu[i,:] == 2).sum()
    insitu_hist[i,3] = (insitu[i,:] == 3).sum()
    insitu_hist[i,:] = insitu_hist[i,:]/len(insitu[i,:])
    print(np.sum(insitu_hist[i,:]))
    #pyplot.figure(i*4+1)
    pyplot.bar([0,1,2,3],insitu_hist[i,:],1,0,'center')
    pyplot.xlabel('0:Benign 1:InSitu 2:Invasive 3:Normal')
    pyplot.ylabel('Percent')
    pyplot.title('InSitu'+str(i))
    pyplot.savefig('/home/Drive2/aditya/Histograms/InSitu_'+str(i)+'.png')    
    pyplot.close()

    invasive_hist[i,0] = (invasive[i,:] == 0).sum()
    invasive_hist[i,1] = (invasive[i,:] == 1).sum()
    invasive_hist[i,2] = (invasive[i,:] == 2).sum()
    invasive_hist[i,3] = (invasive[i,:] == 3).sum()
    invasive_hist[i,:] = invasive_hist[i,:]/len(invasive[i,:])
    print(np.sum(invasive_hist[i,:]))
    #pyplot.figure(i*4+2)
    pyplot.bar([0,1,2,3],invasive_hist[i,:],1,0,'center')
    pyplot.xlabel('0:Benign 1:InSitu 2:Invasive 3:Normal')
    pyplot.ylabel('Percent')
    pyplot.title('Invasive'+str(i))
    pyplot.savefig('/home/Drive2/aditya/Histograms/Invasive_'+str(i)+'.png')
    pyplot.close()

    normal_hist[i,0] = (normal[i,:] == 0).sum()
    normal_hist[i,1] = (normal[i,:] == 1).sum()
    normal_hist[i,2] = (normal[i,:] == 2).sum()
    normal_hist[i,3] = (normal[i,:] == 3).sum()
    normal_hist[i,:] = normal_hist[i,:]/len(normal[i,:])
    print(np.sum(normal_hist[i,:]))
    #pyplot.figure(i*4+3)
    pyplot.bar([0,1,2,3],normal_hist[i,:],1,0,'center')
    pyplot.xlabel('0:Benign 1:InSitu 2:Invasive 3:Normal')
    pyplot.ylabel('Percent')
    pyplot.title('Normal'+str(i))
    pyplot.savefig('/home/Drive2/aditya/Histograms/Normal_'+str(i)+'.png')
    pyplot.close()

